version: 2.1

jobs:
  build:
    docker:
      - image: node:12.16.1
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
